### ISSUE TITLE
Using the /static directory

### ISSUE THREAD

**Issue by dannguyen** [squidnee/compjour-hw#1]
One cosmetic thing: if you're wondering why stylesheets/index.css doesn't seem to be working, it's because in development, the webserver expects things to be in /static, i.e. in /static/stylesheets/index.css

And then refer to them as an absolute path:

```
             <link rel="stylesheet" href="/static/stylesheets/index.css">
```

http://flask.pocoo.org/docs/0.10/quickstart/#static-files

**Comment by squidnee** [comment]
Ah, thanks for that tip. I'll update the name of the folder to make things easier.
